project_me/config/routes.rb
ProjectMe::Application.routes.draw do
  resources :wiki_pages

  resources :time_reports

  resources :tasks

  resources :projects

  resources :documents

end

project_me/app/models/time_report.rb
class TimeReport < ActiveRecord::Base
  belongs_to :task
  attr_accessible :started, :stopped
end

project_me/app/controllers/time_reports_controller.rb
class TimeReportsController < ApplicationController
  # GET /time_reports
  # GET /time_reports.json
  def index
    @time_reports = TimeReport.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @time_reports }
    end
  end

  # GET /time_reports/1
  # GET /time_reports/1.json
  def show
    @time_report = TimeReport.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @time_report }
    end
  end

  # GET /time_reports/new
  # GET /time_reports/new.json
  def new
    @time_report = TimeReport.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @time_report }
    end
  end

  # GET /time_reports/1/edit
  def edit
    @time_report = TimeReport.find(params[:id])
  end

  # POST /time_reports
  # POST /time_reports.json
  def create
    @time_report = TimeReport.new(params[:time_report])

    respond_to do |format|
      if @time_report.save
        format.html { redirect_to @time_report, notice: 'Time report was successfully created.' }
        format.json { render json: @time_report, status: :created, location: @time_report }
      else
        format.html { render action: "new" }
        format.json { render json: @time_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /time_reports/1
  # PUT /time_reports/1.json
  def update
    @time_report = TimeReport.find(params[:id])

    respond_to do |format|
      if @time_report.update_attributes(params[:time_report])
        format.html { redirect_to @time_report, notice: 'Time report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @time_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_reports/1
  # DELETE /time_reports/1.json
  def destroy
    @time_report = TimeReport.find(params[:id])
    @time_report.destroy

    respond_to do |format|
      format.html { redirect_to time_reports_url }
      format.json { head :no_content }
    end
  end
end

project_me/app/helpers/time_reports_helper.rb
module TimeReportsHelper
end

project_me/app/views/time_reports/_form.html.erb
<%= form_for(@time_report) do |f| %>
  <% if @time_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_report.errors.count, "error") %> prohibited this time_report from being saved:</h2>

      <ul>
      <% @time_report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :started %><br />
    <%= f.datetime_select :started %>
  </div>
  <div class="field">
    <%= f.label :stopped %><br />
    <%= f.datetime_select :stopped %>
  </div>
  <div class="field">
    <%= f.label :task %><br />
    <%= f.text_field :task %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project_me/app/views/time_reports/edit.html.erb
<h1>Editing time_report</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_report %> |
<%= link_to 'Back', time_reports_path %>

project_me/app/views/time_reports/index.html.erb
<h1>Listing time_reports</h1>

<table>
  <tr>
    <th>Started</th>
    <th>Stopped</th>
    <th>Task</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @time_reports.each do |time_report| %>
  <tr>
    <td><%= time_report.started %></td>
    <td><%= time_report.stopped %></td>
    <td><%= time_report.task %></td>
    <td><%= link_to 'Show', time_report %></td>
    <td><%= link_to 'Edit', edit_time_report_path(time_report) %></td>
    <td><%= link_to 'Destroy', time_report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Time report', new_time_report_path %>

project_me/app/views/time_reports/new.html.erb
<h1>New time_report</h1>

<%= render 'form' %>

<%= link_to 'Back', time_reports_path %>

project_me/app/views/time_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Started:</b>
  <%= @time_report.started %>
</p>

<p>
  <b>Stopped:</b>
  <%= @time_report.stopped %>
</p>

<p>
  <b>Task:</b>
  <%= @time_report.task %>
</p>


<%= link_to 'Edit', edit_time_report_path(@time_report) %> |
<%= link_to 'Back', time_reports_path %>