project_me/config/routes.rb
ProjectMe::Application.routes.draw do
  resources :wiki_pages

  resources :time_reports

  resources :tasks

  resources :projects

  resources :documents

end

project_me/app/models/wiki_page.rb
class WikiPage < ActiveRecord::Base
  belongs_to :project
  attr_accessible :body, :title
end

project_me/app/controllers/wiki_pages_controller.rb
class WikiPagesController < ApplicationController
  # GET /wiki_pages
  # GET /wiki_pages.json
  def index
    @wiki_pages = WikiPage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wiki_pages }
    end
  end

  # GET /wiki_pages/1
  # GET /wiki_pages/1.json
  def show
    @wiki_page = WikiPage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wiki_page }
    end
  end

  # GET /wiki_pages/new
  # GET /wiki_pages/new.json
  def new
    @wiki_page = WikiPage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wiki_page }
    end
  end

  # GET /wiki_pages/1/edit
  def edit
    @wiki_page = WikiPage.find(params[:id])
  end

  # POST /wiki_pages
  # POST /wiki_pages.json
  def create
    @wiki_page = WikiPage.new(params[:wiki_page])

    respond_to do |format|
      if @wiki_page.save
        format.html { redirect_to @wiki_page, notice: 'Wiki page was successfully created.' }
        format.json { render json: @wiki_page, status: :created, location: @wiki_page }
      else
        format.html { render action: "new" }
        format.json { render json: @wiki_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wiki_pages/1
  # PUT /wiki_pages/1.json
  def update
    @wiki_page = WikiPage.find(params[:id])

    respond_to do |format|
      if @wiki_page.update_attributes(params[:wiki_page])
        format.html { redirect_to @wiki_page, notice: 'Wiki page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wiki_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wiki_pages/1
  # DELETE /wiki_pages/1.json
  def destroy
    @wiki_page = WikiPage.find(params[:id])
    @wiki_page.destroy

    respond_to do |format|
      format.html { redirect_to wiki_pages_url }
      format.json { head :no_content }
    end
  end
end

project_me/app/helpers/wiki_pages_helper.rb
module WikiPagesHelper
end

project_me/app/views/wiki_pages/_form.html.erb
<%= form_for(@wiki_page) do |f| %>
  <% if @wiki_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wiki_page.errors.count, "error") %> prohibited this wiki_page from being saved:</h2>

      <ul>
      <% @wiki_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :project %><br />
    <%= f.text_field :project %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project_me/app/views/wiki_pages/edit.html.erb
<h1>Editing wiki_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @wiki_page %> |
<%= link_to 'Back', wiki_pages_path %>

project_me/app/views/wiki_pages/index.html.erb
<h1>Listing wiki_pages</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wiki_pages.each do |wiki_page| %>
  <tr>
    <td><%= wiki_page.title %></td>
    <td><%= wiki_page.body %></td>
    <td><%= wiki_page.project %></td>
    <td><%= link_to 'Show', wiki_page %></td>
    <td><%= link_to 'Edit', edit_wiki_page_path(wiki_page) %></td>
    <td><%= link_to 'Destroy', wiki_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wiki page', new_wiki_page_path %>

project_me/app/views/wiki_pages/new.html.erb
<h1>New wiki_page</h1>

<%= render 'form' %>

<%= link_to 'Back', wiki_pages_path %>

project_me/app/views/wiki_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @wiki_page.title %>
</p>

<p>
  <b>Body:</b>
  <%= @wiki_page.body %>
</p>

<p>
  <b>Project:</b>
  <%= @wiki_page.project %>
</p>


<%= link_to 'Edit', edit_wiki_page_path(@wiki_page) %> |
<%= link_to 'Back', wiki_pages_path %>